### ISSUE TITLE
Registration functionality is not working.

### ISSUE THREAD

**Issue by abel406** [knpuniversity/javascript#2]
On production enviroment i get this:

> Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused. 

On development enviroment i get this:

>  Class "fos_user.model.user.class" not found. Is the "data_class" form option set correctly?
500 Internal Server Error - InvalidArgumentException 

Any comments ?

**Comment by abel406** [comment]
I already know what is the cause. 

In my services.yml file the code was as following:
`services:

    app.form.type.registration_type:
        class: AppBundle\Form\Type\RegistrationType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type }`
But there was a deprecation message about Not quoting a scalar starting with the % indicator character, deprecated since Symfony 3.1

I changed it after starting the Tutorial to this `services:

    app.form.type.registration_type:
        class: AppBundle\Form\Type\RegistrationType
        arguments: [fos_user.model.user.class]
        tags:
            - { name: form.type }` and that is why i couldn't get the registration form properly.

Sorry for submitting an issue for this.

**Comment by abel406** [comment]
According to @javiereguiluz [issue](https://github.com/symfony/symfony-demo/issues/246), the fix for this deprecation in the tutorial code should be:

services:

    app.form.type.registration_type:
        class: AppBundle\Form\Type\RegistrationType
        arguments: ['%fos_user.model.user.class%']
        tags:
            - { name: form.type } 
with single  quotes instead of double quotes.
I hope this help someone.

**Comment by weaverryan** [comment]
Thanks for the issue! You're right about the deprecated, unquoted strings! I just fixed it at sha: fb92ec18a60dfe431af658d4a410f378adce659d

Thank you!
